version: '3.3'

services:
  nginx:
    image: underr/simplezat-nginx:stable
    ports:
      - "8000:80"
    volumes:
      - app-staticfiles:/app/static
    depends_on:
      - app

  db:
    image: postgres:11.1-alpine
    volumes:
      - postgres-data:/var/liv/postgresql/data

  app:
    image: underr/simplezat:stable
    volumes:
      - app-staticfiles:/app/static
    command: ./entrypoint.dev.sh
    depends_on:
      - db 

volumes:
  postgres-data:
  app-staticfiles:
