version: '3.3'

services:
  db:
    image: postgres:11.1
    volumes:
      - postgres-data:/var/liv/postgresql/data

  app:
    image: underr/simplezat:unstable
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    command: ./entrypoint.sh

volumes:
  postgres-data:
