version: 2
jobs:
  checkout_code:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  python_dependencies:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            pipenv install --dev

  static_analysis:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Static Analysis 
          command: |
            pipenv install --dev
            pipenv run flake8

  unit_tests:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Unittest 
          command: |
            pipenv install --dev
            cd simplezat
            pipenv run python manage.py test

  deploy_dev:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Stable Images
          command: |
            docker build -t underr/simplezat:stable -f Dockerfile.dev .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push underr/simplezat:stable
      - add_ssh_keys:
          fingerprints:
            - "86:82:d2:ca:66:35:3d:4c:35:fb:9a:71:18:91:0a:d0"
      - run:
          name: Deploy to Development Server 
          command: |
            cd deployment
            ssh-keyscan -H 35.244.119.112 >> ~/.ssh/known_hosts
            pipenv install
            pipenv run ansible-playbook -i server_hosts playbooks/dev.yml --extra-vars "project_root=~/simplezat"

  deploy_production:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Live Images
          command: |
            docker build -t underr/simplezat:live -f Dockerfile.production .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push underr/simplezat:live
      - add_ssh_keys:
          fingerprints:
            - "86:82:d2:ca:66:35:3d:4c:35:fb:9a:71:18:91:0a:d0"
      - run:
          name: Deploy to Production Server 
          command: |
            cd deployment
            ssh-keyscan -H 35.244.109.21 >> ~/.ssh/known_hosts
            pipenv install
            pipenv run ansible-playbook -i server_hosts playbooks/prod.yml --extra-vars "project_root=~/simplezat"

workflows:
  version: 2
  simplezat_pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - static_analysis:
          requires:
            - python_dependencies
      - unit_tests:
          requires:
            - python_dependencies
      - deploy_dev:
          requires:
            - unit_tests
      - wait_for_approval:
          type: approval
          requires:
            - deploy_dev 
      - deploy_production:
          requires:
            - wait_for_approval 
