version: 2
jobs:
  checkout_code:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  python_dependencies:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            pipenv install --dev

  static_analysis:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Static Analysis 
          command: |
            pipenv install --dev
            pipenv run flake8

  unit_tests:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
      - image: circleci/postgres:11.1-alpine-ram
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Unittest 
          command: |
            pipenv install --dev
            cd simplezat
            export DATABASE_HOST=localhost pipenv run pytest

  deploy_dev:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Stable Images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t underr/simplezat-nginx:stable -f nginx/Dockerfile nginx/
            docker tag underr/simplezat-nginx:stable underr/simplezat-nginx:$CIRCLE_SHA1
            docker push underr/simplezat-nginx:stable
            docker build -t underr/simplezat:stable -f Dockerfile.dev .
            docker tag underr/simplezat:stable underr/simplezat:$CIRCLE_SHA1
            docker push underr/simplezat:stable
            docker push underr/simplezat:$CIRCLE_SHA1
      - add_ssh_keys:
          fingerprints:
            - "86:82:d2:ca:66:35:3d:4c:35:fb:9a:71:18:91:0a:d0"
      - run:
          name: Deploy to Development Server 
          command: |
            cd deployment
            ssh-keyscan -H 35.244.119.112 >> ~/.ssh/known_hosts
            pipenv install
            pipenv run ansible-playbook -i server_hosts playbooks/dev.yml --extra-vars "project_root=~/simplezat"

  acceptance_tests:
    working_directory: ~/simplezat
    docker:
      - image: circleci/node:8.14-browsers
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Acceptance Test
          command: |
            cd tests
            npm install
            CYPRESS_baseUrl=http://35.244.119.112:8000 ./node_modules/.bin/cypress run --spec "cypress/integration/simplezat/*"

  deploy_production:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Live Images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull underr/simplezat-nginx:stable
            docker tag underr/simplezat-nginx:stable underr/simplezat-nginx:live
            docker push underr/simplezat-nginx:live
            docker build -t underr/simplezat:live -f Dockerfile.production .
            docker tag underr/simplezat:live underr/simplezat:$CIRCLE_SHA1
            docker push underr/simplezat:live
            docker push underr/simplezat:$CIRCLE_SHA1
      - add_ssh_keys:
          fingerprints:
            - "86:82:d2:ca:66:35:3d:4c:35:fb:9a:71:18:91:0a:d0"
      - run:
          name: Deploy to Production Server 
          command: |
            cd deployment
            ssh-keyscan -H 35.244.109.21 >> ~/.ssh/known_hosts
            pipenv install
            pipenv run ansible-playbook -i server_hosts playbooks/prod.yml --extra-vars "project_root=~/simplezat"

workflows:
  version: 2
  simplezat_pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - static_analysis:
          requires:
            - python_dependencies
      - unit_tests:
          requires:
            - python_dependencies
      - deploy_dev:
          requires:
            - unit_tests
      - acceptance_tests:
          requires:
            - deploy_dev
      - wait_for_approval:
          type: approval
          requires:
            - acceptance_tests 
      - deploy_production:
          requires:
            - wait_for_approval 
